Rename hoverableText.tsx to HoverableText.tsx
I think the error that I am getting in deployment which is this:

Type error: Cannot find module '@/components/HoverableText' or its corresponding type declarations.

Is due to the fact that the file is lowerCase and not LowerCase